name: chucknorris
adopt-info: chucknorris
summary: Chuck Norris in your terminal!
description: |
  Increase your smile reading these awesome Chuck Norris jokes from your terminal! 
  Disclaimer: Chuck Norris doesn't joke, he'll just tell you when to laugh.

license: MIT

base: core20
grade: stable 
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf
  - build-on: ppc64el
  - build-on: s390x
  
apps:
  chucknorris:
    command: bin/chucknorris
    environment:
      LC_ALL: C.UTF-8

parts: 
  chucknorris:
    source: https://github.com/kz6fittycent/Chuck_Norris
    source-type: git
    plugin: python

    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version "$(git describe --tags | sed 's/^v//' | cut -d "-" -f1)"  
